[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
umanity_donations = "BW8QEjNXreRdzHoQP8C2uRZaZu5pqZD6VK4f6yidpQ1P"
umanity_tips = "5hkEjoNLyEpgKezYBvU2HF1FgBHfKGqumBaT48moUwqJ"

[programs.devnet]
umanity_donations = "BW8QEjNXreRdzHoQP8C2uRZaZu5pqZD6VK4f6yidpQ1P"
umanity_tips = "5hkEjoNLyEpgKezYBvU2HF1FgBHfKGqumBaT48moUwqJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
